name: Pipeline and Merge to Main

on:
  push:
    tags:
      - registration

jobs:
  build-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pipeline
        run: ./run-pipeline.sh

      - name:  main
        uses: peaceiris/actions@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
